import React, { useState } from 'react';
import { X, Copy, Share, Check, Terminal } from 'lucide-react';
import { Artifact } from '../types';

interface ArtifactPanelProps {
  isOpen: boolean;
  artifact: Artifact | null;
  onClose: () => void;
  style?: React.CSSProperties;
}

const ArtifactPanel: React.FC<ArtifactPanelProps> = ({ isOpen, artifact, onClose, style }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !artifact) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(artifact.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div 
      className="h-full bg-white border-l border-[#E5E2DA] shadow-sm z-10 flex flex-col overflow-hidden"
      style={style}
    >
      {/* Header */}
      <div className="h-12 border-b border-[#E5E2DA] flex items-center justify-between px-4 bg-[#FAFAF8] shrink-0">
        <div className="flex items-center gap-2 text-sm text-gray-500">
           <span className="font-mono text-xs uppercase bg-gray-100 px-1.5 py-0.5 rounded border border-gray-200">
             {artifact.language || 'TEXT'}
           </span>
           <span className="truncate max-w-[200px] font-medium text-gray-700">{artifact.title}</span>
        </div>
        
        <div className="flex items-center gap-2">
           <button 
             onClick={handleCopy}
             className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md hover:bg-gray-100 text-xs font-medium text-gray-600 transition-colors border border-transparent hover:border-gray-200"
           >
             {copied ? <Check size={14} className="text-green-600" /> : <Copy size={14} />}
             {copied ? 'Copied' : 'Copy'}
           </button>
           
           <button className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-claude-text text-white text-xs font-medium hover:bg-black transition-colors shadow-sm">
             Publish
           </button>
           
           <button 
             onClick={onClose}
             className="p-1.5 rounded-md hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors ml-1"
           >
             <X size={16} />
           </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto bg-white">
        <div className="p-4 min-h-full">
            <pre className="font-mono text-[13px] leading-relaxed text-[#24292e] whitespace-pre-wrap break-words">
                <code>{artifact.content}</code>
            </pre>
        </div>
      </div>
      
      {/* Footer */}
      <div className="h-8 border-t border-[#E5E2DA] bg-[#FAFAF8] flex items-center px-4 text-[10px] text-gray-400 justify-between shrink-0">
         <span>Generated by Claude</span>
         <span className="font-mono">Ln {artifact.content.split('\n').length}, Col 0</span>
      </div>
    </div>
  );
};

export default ArtifactPanel;